import '../assets/styles/variables.css';
import '../assets/styles/base.css';
import '../assets/styles/icons.css';
import '../assets/styles/buttons.css';
import '../assets/styles/dashboard.css';
import '../assets/styles/layout.css';
import '../assets/styles/slider.css';
import '../assets/styles/status.css';
import '../assets/styles/stdout.css';
